name: Convert html files to APK

on:
  push:
    branches:
      - main
    paths:
      - '**.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "apk_files"
  cancel-in-progress: false    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 0 - Checkout - put the repository files into the Github Actions runner
        uses: actions/checkout@v4
        
      - name: Step 1 - Setup/install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
        
      - name: Step 2 - use the html to apk conversion
        uses: darkshredder/web-to-app-action@main
        with:
          build-folder-path: "./src_apks" # Defaults to build, It is the folder where build files or html are stored
          app-name: "Url-to-pdf viewer"
          output-folder-path: "./dist_apks/" # Defaults to apk/, Where final APK files are created
    
      - name: Step 3 - Upload Artifact (Save created files from runner to repository)
        uses: actions/upload-artifact@v4
        with:
          name: Final-apks
          path: ./dist_apks/ # Should be same as "output-folder-path"
